"""empty message

Revision ID: 0de32ef12238
Revises: 9a6f6e18256f
Create Date: 2022-08-24 15:27:00.540278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de32ef12238'
down_revision = '9a6f6e18256f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_id', table_name='items')
    op.drop_table('items')
    op.drop_index('ix_OrderItems_id', table_name='OrderItems')
    op.drop_table('OrderItems')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OrderItems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"OrderItems_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('products', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['products'], ['Product.id'], name='OrderItems_products_fkey'),
    sa.PrimaryKeyConstraint('id', name='OrderItems_pkey')
    )
    op.create_index('ix_OrderItems_id', 'OrderItems', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['User.id'], name='items_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.create_index('ix_items_id', 'items', ['id'], unique=False)
    # ### end Alembic commands ###
