"""empty message

Revision ID: 1ab4cb4dedf3
Revises: 0de32ef12238
Create Date: 2022-08-24 18:52:42.324848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab4cb4dedf3'
down_revision = '0de32ef12238'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
