"""empty message

Revision ID: 9a6f6e18256f
Revises: bd6ac1e52403
Create Date: 2022-08-23 15:56:15.256560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a6f6e18256f'
down_revision = 'bd6ac1e52403'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Orders_cart_fkey', 'Orders', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Orders_cart_fkey', 'Orders', 'Cart', ['cart'], ['id'])
    # ### end Alembic commands ###
