"""empty message

Revision ID: b6339314fc9b
Revises: 1ab4cb4dedf3
Create Date: 2022-08-24 18:57:51.951055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6339314fc9b'
down_revision = '1ab4cb4dedf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
