"""empty message

Revision ID: bd6ac1e52403
Revises: 0073bf16cfbf
Create Date: 2022-08-23 14:12:34.885208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd6ac1e52403'
down_revision = '0073bf16cfbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
